# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DEMaP <- function(gfrom, gto, gw, NbNodes, dep, arr, embedding) {
    .Call('_snnMAP_DEMaP', PACKAGE = 'snnMAP', gfrom, gto, gw, NbNodes, dep, arr, embedding)
}

DEMaP_par <- function(gfrom, gto, gw, NbNodes, dep, arr, embedding) {
    .Call('_snnMAP_DEMaP_par', PACKAGE = 'snnMAP', gfrom, gto, gw, NbNodes, dep, arr, embedding)
}

optimize_layout_r <- function(head_embedding, tail_embedding, positive_head, positive_tail, positive_ptr, n_epochs, n_head_vertices, n_tail_vertices, epochs_per_sample, method, method_args, initial_alpha, opt_args, epoch_callback, negative_sample_rate, pcg_rand = TRUE, batch = FALSE, n_threads = 0L, grain_size = 1L, move_other = TRUE, verbose = FALSE) {
    .Call('_snnMAP_optimize_layout_r', PACKAGE = 'snnMAP', head_embedding, tail_embedding, positive_head, positive_tail, positive_ptr, n_epochs, n_head_vertices, n_tail_vertices, epochs_per_sample, method, method_args, initial_alpha, opt_args, epoch_callback, negative_sample_rate, pcg_rand, batch, n_threads, grain_size, move_other, verbose)
}

rcpp_distance <- function(mat, X, Y) {
    .Call('_snnMAP_rcpp_distance', PACKAGE = 'snnMAP', mat, X, Y)
}

